### ISSUE TITLE
More examples available?

### ISSUE THREAD

**Issue by d1vachev** [LukeSkywalker92/pyTMCL#3]
Hi all,

I am quite new to controlling steppers with python and i was wondering if someone can send or point me to more code examples using pyTMCL. Any help will be greatly appreciated!:)

**Comment by LukeSkywalker92** [comment]
Hey,

what kind of examples do you expect? Maybe you can tell us what you are planning to do.. I assume you already looked at the examples folder.

**Comment by d1vachev** [comment]
Hi Luke,

I was stuck on the axis parameters but figured it out. thanks  for the reply!
